In [19]:
import pandas as pd

hotel_df = pd.read_csv("WeatherPy_vacation.csv")
hotel_df.head(50)

,City,City.1,Country,Max Temp,Weather Description,Lat,Lng,Hotel Name
0,2,Albany,US,84.00,clear sky,42.60,-73.97,NaN
1,7,Bethel,US,82.40,clear sky,41.37,-73.41,NaN
2,11,Hithadhoo,MV,84.83,broken clouds,-0.60,73.08,NaN
3,14,Butaritari,KI,83.71,broken clouds,3.07,172.79,NaN
4,29,Basco,PH,84.76,broken clouds,20.45,121.97,NaN
5,38,Garowe,SO,77.90,broken clouds,8.41,48.48,NaN
6,47,Kandiaro,PK,89.80,clear sky,27.06,68.21,NaN
7,51,The Valley,AI,84.20,scattered clouds,18.22,-63.06,NaN
8,59,Kalmunai,LK,80.19,overcast clouds,7.42,81.82,NaN
9,60,Hilo,US,82.40,few clouds,19.73,-155.09,NaN
10,74,Awbari,LY,84.24,clear sky,26.59,12.78,NaN
11,79,Trincomalee,LK,80.65,overcast clouds,8.57,81.23,NaN
12,87,Sorong,ID,79.00,clear sky,-0.88,131.25,NaN
13,88,Lengshuitan,CN,82.81,overcast clouds,26.41,111.60,NaN
14,91,Tabuk,PH,80.96,overcast clouds,17.42,121.44,NaN
15,93,San Jose,US,93.99,clear sky,37.34,-121.89,NaN
16,100,Lakatoro,VU,80.60,broken clouds,-16.10,167.42,NaN
17,102,Portland,US,77.00,scattered clouds,45.52,-122.68,NaN
18,103,Umm Lajj,SA,82.94,scattered clouds,25.02,37.27,NaN
19,105,San Patricio,MX,87.80,scattered clouds,19.22,-104.70,NaN
20,108,Biltine,TD,87.40,broken clouds,14.53,20.92,NaN
21,109,Aswan,EG,82.85,few clouds,24.09,32.91,NaN
22,114,Georgetown,MY,80.60,few clouds,5.41,100.34,NaN
23,121,Pizarro,CO,78.64,broken clouds,4.95,-77.37,NaN
24,124,Nishihara,JP,86.00,broken clouds,26.18,127.76,NaN
25,125,Jeremie,HT,81.99,scattered clouds,18.65,-74.12,NaN
26,126,Atuona,PF,79.83,clear sky,-9.80,-139.03,NaN
27,131,Daudnagar,IN,85.96,broken clouds,25.03,84.40,NaN
28,137,Marzuq,YE,82.02,broken clouds,14.40,46.47,NaN
29,139,Matara,LK,78.80,overcast clouds,5.95,80.54,NaN
30,142,Manaure,CO,83.82,few clouds,11.78,-72.44,NaN
31,145,Pacific Grove,US,77.00,clear sky,36.62,-121.92,NaN
32,148,Katobu,ID,78.62,few clouds,-4.94,122.53,NaN
33,149,Hami,CN,76.91,broken clouds,42.80,93.45,NaN
34,151,Bandarbeyla,SO,82.06,broken clouds,9.49,50.81,NaN
35,154,Faanui,PF,79.02,overcast clouds,-16.48,-151.75,NaN
36,158,Isangel,VU,78.80,broken clouds,-19.55,169.27,NaN
37,160,Atambua,ID,76.32,overcast clouds,-9.11,124.89,NaN
38,162,Morant Bay,JM,87.80,few clouds,17.88,-76.41,NaN
39,165,Atyrau,KZ,77.00,clear sky,47.12,51.88,NaN
40,174,Cayenne,GF,78.80,light rain,4.93,-52.33,NaN
41,182,Kidal,ML,87.98,scattered clouds,18.44,1.41,NaN
42,185,Belaya Gora,RU,75.88,overcast clouds,68.53,146.42,NaN
43,191,Tual,ID,79.07,scattered clouds,-5.67,132.75,NaN
44,194,Bemidji,US,80.01,broken clouds,47.47,-94.88,NaN
45,197,Yanam,IN,80.98,overcast clouds,16.73,82.22,NaN
46,199,Leshan,CN,75.33,overcast clouds,29.56,103.76,NaN
47,205,Kahului,US,89.60,scattered clouds,20.89,-156.47,NaN
48,208,Puerto Escondido,MX,86.00,broken clouds,15.85,-97.07,NaN
49,211,Nabire,ID,81.72,overcast clouds,-3.37,135.48,NaN

In [23]:
#data frames
avera_df = hotel_df.loc[hotel_df["City.1"]=="Avera"] 
virginia_beach_df = hotel_df.loc[hotel_df["City.1"]=="Virginia Beach"]
marion_df =  hotel_df.loc[hotel_df["City.1"]=="Marion"]
windsor_df =  hotel_df.loc[hotel_df["City.1"]=="Windsor"]
windsor_df

,City,City.1,Country,Max Temp,Weather Description,Lat,Lng,Hotel Name
131,481,Windsor,CA,82.0,scattered clouds,42.3,-83.02,NaN

In [25]:
import gmaps
import gmaps.datasets
import requests
# Import the API key.
from config import g_key 

# configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

#lat-long
avera = (33.19,-82.53)
virginia_beach = (36.85, -75.98)
mairon = (39.77, -86.16)
windsor = (42.2, -83.02)

fig = gmaps.figure()
fourcities = gmaps.directions_layer(avera, virginia_beach, waypoints=[mairon, windsor], travel_mode='DRIVING')
fig.add_layer(fourcities)
fig

Figure(layout=FigureLayout(height='420px'))